site_name: My Docs
theme:
  name: material
nav:
  - Home: index.md
  - Core: core.md
  - Drawing: drawing.md
  - Coloring: coloring.md
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_type_in_signature: true
            show_signature_annotations: true
            separate_signature: false 
            show_symbol_type_heading: true
            # show_if_no_docstring: false
            signature_crossrefs: true
            # merge_init_into_class: true
            extensions:
              - griffe_fieldz: {include_inherited: true}

